CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created TIMESTAMP NOT NULL,
  modified TIMESTAMP NOT NULL,
  last_login TIMESTAMP NOT NULL,
  token VARCHAR(255) NOT NULL,
  is_active BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS phones (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  number VARCHAR(32) NOT NULL,
  citycode VARCHAR(16) NOT NULL,
  contrycode VARCHAR(16) NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  CONSTRAINT fk_phone_user FOREIGN KEY (user_id) REFERENCES users(id)
);
